# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/durand/Documents/SeisTomoPy_V3.0/SeisTomoPy/gui/qt_window.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SeisTomoPy(object):
    def setupUi(self, SeisTomoPy):
        SeisTomoPy.setObjectName("SeisTomoPy")
        SeisTomoPy.resize(1136, 720)
        self.centralwidget = QtWidgets.QWidget(SeisTomoPy)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 0, 1091, 751))
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.Welcome = QtWidgets.QWidget()
        self.Welcome.setObjectName("Welcome")
        self.label_42 = QtWidgets.QLabel(self.Welcome)
        self.label_42.setGeometry(QtCore.QRect(80, 110, 911, 41))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        font.setPointSize(20)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.Welcome)
        self.label_43.setGeometry(QtCore.QRect(0, 580, 911, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.Welcome)
        self.label_44.setGeometry(QtCore.QRect(0, 600, 911, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.mapfig_intro2 = Qt5MplCanvas(self.Welcome)
        self.mapfig_intro2.setEnabled(True)
        self.mapfig_intro2.setGeometry(QtCore.QRect(80, 170, 921, 401))
        self.mapfig_intro2.setMinimumSize(QtCore.QSize(150, 100))
        self.mapfig_intro2.setMaximumSize(QtCore.QSize(1000, 600))
        self.mapfig_intro2.setObjectName("mapfig_intro2")
        self.mapfig_intro1 = Qt5MplCanvas(self.Welcome)
        self.mapfig_intro1.setEnabled(True)
        self.mapfig_intro1.setGeometry(QtCore.QRect(470, 20, 161, 71))
        self.mapfig_intro1.setMinimumSize(QtCore.QSize(150, 50))
        self.mapfig_intro1.setMaximumSize(QtCore.QSize(1000, 600))
        self.mapfig_intro1.setObjectName("mapfig_intro1")
        self.label_50 = QtWidgets.QLabel(self.Welcome)
        self.label_50.setGeometry(QtCore.QRect(0, 620, 911, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.tabWidget.addTab(self.Welcome, "")
        self.Cross_section = QtWidgets.QWidget()
        self.Cross_section.setObjectName("Cross_section")
        self.label_7 = QtWidgets.QLabel(self.Cross_section)
        self.label_7.setGeometry(QtCore.QRect(860, 450, 99, 18))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.width_cross = QtWidgets.QDoubleSpinBox(self.Cross_section)
        self.width_cross.setGeometry(QtCore.QRect(150, 140, 91, 24))
        self.width_cross.setAlignment(QtCore.Qt.AlignCenter)
        self.width_cross.setDecimals(0)
        self.width_cross.setMinimum(10.0)
        self.width_cross.setMaximum(358.0)
        self.width_cross.setSingleStep(2.0)
        self.width_cross.setProperty("value", 180.0)
        self.width_cross.setObjectName("width_cross")
        self.label_5 = QtWidgets.QLabel(self.Cross_section)
        self.label_5.setGeometry(QtCore.QRect(680, 420, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLineWidth(1)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(self.Cross_section)
        self.label_8.setGeometry(QtCore.QRect(860, 500, 99, 17))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.depth_cross = QtWidgets.QDoubleSpinBox(self.Cross_section)
        self.depth_cross.setGeometry(QtCore.QRect(150, 80, 91, 24))
        self.depth_cross.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_cross.setDecimals(0)
        self.depth_cross.setMinimum(0.0)
        self.depth_cross.setMaximum(2890.0)
        self.depth_cross.setSingleStep(1.0)
        self.depth_cross.setProperty("value", 2890.0)
        self.depth_cross.setObjectName("depth_cross")
        self.label_14 = QtWidgets.QLabel(self.Cross_section)
        self.label_14.setGeometry(QtCore.QRect(120, 220, 131, 20))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayoutWidget = QtWidgets.QWidget(self.Cross_section)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(730, 450, 101, 171))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.midpt_longitude = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.midpt_longitude.setAlignment(QtCore.Qt.AlignCenter)
        self.midpt_longitude.setDecimals(0)
        self.midpt_longitude.setMinimum(-180.0)
        self.midpt_longitude.setMaximum(180.0)
        self.midpt_longitude.setObjectName("midpt_longitude")
        self.gridLayout.addWidget(self.midpt_longitude, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.midpt_latitude = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.midpt_latitude.setAlignment(QtCore.Qt.AlignCenter)
        self.midpt_latitude.setDecimals(0)
        self.midpt_latitude.setMinimum(-90.0)
        self.midpt_latitude.setMaximum(90.0)
        self.midpt_latitude.setObjectName("midpt_latitude")
        self.gridLayout.addWidget(self.midpt_latitude, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.azimuth = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.azimuth.setAlignment(QtCore.Qt.AlignCenter)
        self.azimuth.setDecimals(0)
        self.azimuth.setMaximum(360.0)
        self.azimuth.setObjectName("azimuth")
        self.gridLayout.addWidget(self.azimuth, 6, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.Cross_section)
        self.label_10.setGeometry(QtCore.QRect(110, 10, 181, 20))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.Cross_section)
        self.label_4.setGeometry(QtCore.QRect(880, 460, 71, 41))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.Vmax_cross = QtWidgets.QDoubleSpinBox(self.Cross_section)
        self.Vmax_cross.setGeometry(QtCore.QRect(150, 30, 91, 24))
        self.Vmax_cross.setAlignment(QtCore.Qt.AlignCenter)
        self.Vmax_cross.setDecimals(1)
        self.Vmax_cross.setMaximum(20.0)
        self.Vmax_cross.setSingleStep(0.5)
        self.Vmax_cross.setProperty("value", 2.0)
        self.Vmax_cross.setObjectName("Vmax_cross")
        self.earthquake = QtWidgets.QCheckBox(self.Cross_section)
        self.earthquake.setGeometry(QtCore.QRect(880, 590, 111, 18))
        self.earthquake.setChecked(True)
        self.earthquake.setObjectName("earthquake")
        self.label_6 = QtWidgets.QLabel(self.Cross_section)
        self.label_6.setGeometry(QtCore.QRect(850, 420, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLineWidth(1)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.Cross_section)
        self.label_9.setGeometry(QtCore.QRect(880, 510, 71, 41))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.parameter_cross = QtWidgets.QComboBox(self.Cross_section)
        self.parameter_cross.setGeometry(QtCore.QRect(140, 240, 91, 26))
        self.parameter_cross.setEditable(False)
        self.parameter_cross.setMaxVisibleItems(3)
        self.parameter_cross.setDuplicatesEnabled(True)
        self.parameter_cross.setObjectName("parameter_cross")
        self.parameter_cross.addItem("")
        self.parameter_cross.addItem("")
        self.parameter_cross.addItem("")
        self.label_15 = QtWidgets.QLabel(self.Cross_section)
        self.label_15.setGeometry(QtCore.QRect(300, 380, 391, 31))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.savefig_cross = QtWidgets.QPushButton(self.Cross_section)
        self.savefig_cross.setGeometry(QtCore.QRect(840, 130, 131, 32))
        self.savefig_cross.setObjectName("savefig_cross")
        self.plot_cross = QtWidgets.QPushButton(self.Cross_section)
        self.plot_cross.setGeometry(QtCore.QRect(850, 90, 110, 32))
        self.plot_cross.setObjectName("plot_cross")
        self.model_cross = QtWidgets.QComboBox(self.Cross_section)
        self.model_cross.setGeometry(QtCore.QRect(120, 190, 131, 26))
        self.model_cross.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.model_cross.setEditable(False)
        self.model_cross.setMaxVisibleItems(4)
        self.model_cross.setDuplicatesEnabled(True)
        self.model_cross.setObjectName("model_cross")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.model_cross.addItem("")
        self.saveoutput_cross = QtWidgets.QPushButton(self.Cross_section)
        self.saveoutput_cross.setGeometry(QtCore.QRect(840, 170, 131, 32))
        self.saveoutput_cross.setObjectName("saveoutput_cross")
        self.label_16 = QtWidgets.QLabel(self.Cross_section)
        self.label_16.setGeometry(QtCore.QRect(300, 350, 471, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setText("")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.mapfig2_cross = Qt5MplCanvas(self.Cross_section)
        self.mapfig2_cross.setEnabled(True)
        self.mapfig2_cross.setGeometry(QtCore.QRect(270, 410, 421, 231))
        self.mapfig2_cross.setMinimumSize(QtCore.QSize(150, 100))
        self.mapfig2_cross.setMaximumSize(QtCore.QSize(470, 280))
        self.mapfig2_cross.setObjectName("mapfig2_cross")
        self.hotspots = QtWidgets.QCheckBox(self.Cross_section)
        self.hotspots.setGeometry(QtCore.QRect(890, 560, 85, 20))
        self.hotspots.setChecked(True)
        self.hotspots.setObjectName("hotspots")
        self.label_12 = QtWidgets.QLabel(self.Cross_section)
        self.label_12.setGeometry(QtCore.QRect(160, 120, 71, 16))
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.Cross_section)
        self.label_11.setGeometry(QtCore.QRect(160, 60, 71, 16))
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_13 = QtWidgets.QLabel(self.Cross_section)
        self.label_13.setGeometry(QtCore.QRect(120, 170, 131, 20))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.mapfig1_cross = Qt5MplCanvas(self.Cross_section)
        self.mapfig1_cross.setEnabled(True)
        self.mapfig1_cross.setGeometry(QtCore.QRect(310, 0, 470, 351))
        self.mapfig1_cross.setMinimumSize(QtCore.QSize(150, 100))
        self.mapfig1_cross.setMaximumSize(QtCore.QSize(470, 400))
        self.mapfig1_cross.setObjectName("mapfig1_cross")
        self.line = QtWidgets.QFrame(self.Cross_section)
        self.line.setGeometry(QtCore.QRect(833, 410, 20, 221))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.Cross_section)
        self.line_2.setGeometry(QtCore.QRect(840, 540, 151, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.Cross_section)
        self.line_3.setGeometry(QtCore.QRect(710, 400, 281, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.Cross_section)
        self.line_4.setGeometry(QtCore.QRect(700, 410, 20, 221))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.Cross_section)
        self.line_5.setGeometry(QtCore.QRect(980, 410, 20, 141))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.Cross_section)
        self.line_6.setGeometry(QtCore.QRect(710, 620, 131, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.HSdeg_cross = QtWidgets.QDoubleSpinBox(self.Cross_section)
        self.HSdeg_cross.setGeometry(QtCore.QRect(140, 290, 91, 24))
        self.HSdeg_cross.setAlignment(QtCore.Qt.AlignCenter)
        self.HSdeg_cross.setDecimals(0)
        self.HSdeg_cross.setMinimum(1.0)
        self.HSdeg_cross.setMaximum(60.0)
        self.HSdeg_cross.setSingleStep(1.0)
        self.HSdeg_cross.setProperty("value", 40.0)
        self.HSdeg_cross.setObjectName("HSdeg_cross")
        self.label_40 = QtWidgets.QLabel(self.Cross_section)
        self.label_40.setGeometry(QtCore.QRect(90, 270, 191, 20))
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.tabWidget.addTab(self.Cross_section, "")
        self.Map = QtWidgets.QWidget()
        self.Map.setObjectName("Map")
        self.label_17 = QtWidgets.QLabel(self.Map)
        self.label_17.setGeometry(QtCore.QRect(110, 10, 181, 20))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.mapfig_map = Qt5MplCanvas(self.Map)
        self.mapfig_map.setEnabled(True)
        self.mapfig_map.setGeometry(QtCore.QRect(310, 0, 470, 351))
        self.mapfig_map.setMinimumSize(QtCore.QSize(150, 100))
        self.mapfig_map.setMaximumSize(QtCore.QSize(470, 400))
        self.mapfig_map.setObjectName("mapfig_map")
        self.Vmax_map = QtWidgets.QDoubleSpinBox(self.Map)
        self.Vmax_map.setGeometry(QtCore.QRect(150, 30, 91, 24))
        self.Vmax_map.setAlignment(QtCore.Qt.AlignCenter)
        self.Vmax_map.setDecimals(1)
        self.Vmax_map.setMaximum(20.0)
        self.Vmax_map.setSingleStep(0.5)
        self.Vmax_map.setProperty("value", 2.0)
        self.Vmax_map.setObjectName("Vmax_map")
        self.label_18 = QtWidgets.QLabel(self.Map)
        self.label_18.setGeometry(QtCore.QRect(120, 130, 131, 20))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.model_map = QtWidgets.QComboBox(self.Map)
        self.model_map.setGeometry(QtCore.QRect(120, 150, 131, 26))
        self.model_map.setEditable(False)
        self.model_map.setMaxVisibleItems(4)
        self.model_map.setDuplicatesEnabled(True)
        self.model_map.setObjectName("model_map")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.model_map.addItem("")
        self.label_19 = QtWidgets.QLabel(self.Map)
        self.label_19.setGeometry(QtCore.QRect(120, 190, 131, 20))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.parameter_map = QtWidgets.QComboBox(self.Map)
        self.parameter_map.setGeometry(QtCore.QRect(140, 210, 91, 26))
        self.parameter_map.setEditable(False)
        self.parameter_map.setMaxVisibleItems(3)
        self.parameter_map.setDuplicatesEnabled(True)
        self.parameter_map.setObjectName("parameter_map")
        self.parameter_map.addItem("")
        self.parameter_map.addItem("")
        self.parameter_map.addItem("")
        self.parameter_map.addItem("")
        self.label_20 = QtWidgets.QLabel(self.Map)
        self.label_20.setGeometry(QtCore.QRect(300, 360, 471, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setText("")
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.savefig_map = QtWidgets.QPushButton(self.Map)
        self.savefig_map.setGeometry(QtCore.QRect(840, 130, 131, 32))
        self.savefig_map.setObjectName("savefig_map")
        self.plot_map = QtWidgets.QPushButton(self.Map)
        self.plot_map.setGeometry(QtCore.QRect(850, 90, 110, 32))
        self.plot_map.setObjectName("plot_map")
        self.hotspots_map = QtWidgets.QCheckBox(self.Map)
        self.hotspots_map.setGeometry(QtCore.QRect(850, 260, 85, 20))
        self.hotspots_map.setChecked(True)
        self.hotspots_map.setObjectName("hotspots_map")
        self.plateboundaries = QtWidgets.QCheckBox(self.Map)
        self.plateboundaries.setGeometry(QtCore.QRect(830, 290, 141, 20))
        self.plateboundaries.setChecked(True)
        self.plateboundaries.setObjectName("plateboundaries")
        self.depth_map = QtWidgets.QDoubleSpinBox(self.Map)
        self.depth_map.setGeometry(QtCore.QRect(150, 90, 91, 24))
        self.depth_map.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_map.setDecimals(0)
        self.depth_map.setMinimum(0.0)
        self.depth_map.setMaximum(2890.0)
        self.depth_map.setSingleStep(1.0)
        self.depth_map.setProperty("value", 2890.0)
        self.depth_map.setObjectName("depth_map")
        self.label_21 = QtWidgets.QLabel(self.Map)
        self.label_21.setGeometry(QtCore.QRect(150, 70, 71, 16))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.saveoutput_map = QtWidgets.QPushButton(self.Map)
        self.saveoutput_map.setGeometry(QtCore.QRect(840, 170, 131, 32))
        self.saveoutput_map.setObjectName("saveoutput_map")
        self.HSdeg_map = QtWidgets.QDoubleSpinBox(self.Map)
        self.HSdeg_map.setGeometry(QtCore.QRect(140, 270, 91, 24))
        self.HSdeg_map.setAlignment(QtCore.Qt.AlignCenter)
        self.HSdeg_map.setDecimals(0)
        self.HSdeg_map.setMinimum(1.0)
        self.HSdeg_map.setMaximum(60.0)
        self.HSdeg_map.setSingleStep(1.0)
        self.HSdeg_map.setProperty("value", 40.0)
        self.HSdeg_map.setObjectName("HSdeg_map")
        self.label_39 = QtWidgets.QLabel(self.Map)
        self.label_39.setGeometry(QtCore.QRect(90, 250, 191, 20))
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.lon0_map = QtWidgets.QDoubleSpinBox(self.Map)
        self.lon0_map.setGeometry(QtCore.QRect(140, 330, 91, 24))
        self.lon0_map.setAlignment(QtCore.Qt.AlignCenter)
        self.lon0_map.setDecimals(0)
        self.lon0_map.setMinimum(-180.0)
        self.lon0_map.setMaximum(180.0)
        self.lon0_map.setSingleStep(1.0)
        self.lon0_map.setProperty("value", 140.0)
        self.lon0_map.setObjectName("lon0_map")
        self.label_41 = QtWidgets.QLabel(self.Map)
        self.label_41.setGeometry(QtCore.QRect(90, 310, 191, 20))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.tabWidget.addTab(self.Map, "")
        self.Spectrum = QtWidgets.QWidget()
        self.Spectrum.setObjectName("Spectrum")
        self.mapfig_spec = Qt5MplCanvas(self.Spectrum)
        self.mapfig_spec.setEnabled(True)
        self.mapfig_spec.setGeometry(QtCore.QRect(200, 0, 681, 351))
        self.mapfig_spec.setMinimumSize(QtCore.QSize(150, 100))
        self.mapfig_spec.setMaximumSize(QtCore.QSize(700, 700))
        self.mapfig_spec.setObjectName("mapfig_spec")
        self.label_22 = QtWidgets.QLabel(self.Spectrum)
        self.label_22.setGeometry(QtCore.QRect(580, 520, 71, 16))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.depth_spec = QtWidgets.QDoubleSpinBox(self.Spectrum)
        self.depth_spec.setGeometry(QtCore.QRect(580, 540, 91, 24))
        self.depth_spec.setAlignment(QtCore.Qt.AlignCenter)
        self.depth_spec.setDecimals(0)
        self.depth_spec.setMinimum(0.0)
        self.depth_spec.setMaximum(2890.0)
        self.depth_spec.setSingleStep(1.0)
        self.depth_spec.setProperty("value", 2890.0)
        self.depth_spec.setObjectName("depth_spec")
        self.label_23 = QtWidgets.QLabel(self.Spectrum)
        self.label_23.setGeometry(QtCore.QRect(220, 370, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.Spectrum)
        self.label_24.setGeometry(QtCore.QRect(690, 520, 131, 20))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.parameter_spec = QtWidgets.QComboBox(self.Spectrum)
        self.parameter_spec.setGeometry(QtCore.QRect(710, 540, 91, 26))
        self.parameter_spec.setEditable(False)
        self.parameter_spec.setMaxVisibleItems(3)
        self.parameter_spec.setDuplicatesEnabled(True)
        self.parameter_spec.setObjectName("parameter_spec")
        self.parameter_spec.addItem("")
        self.parameter_spec.addItem("")
        self.parameter_spec.addItem("")
        self.SEISGLOB2 = QtWidgets.QCheckBox(self.Spectrum)
        self.SEISGLOB2.setGeometry(QtCore.QRect(210, 400, 101, 20))
        self.SEISGLOB2.setChecked(True)
        self.SEISGLOB2.setObjectName("SEISGLOB2")
        self.S40RTS = QtWidgets.QCheckBox(self.Spectrum)
        self.S40RTS.setGeometry(QtCore.QRect(210, 430, 101, 20))
        self.S40RTS.setChecked(True)
        self.S40RTS.setObjectName("S40RTS")
        self.SEMUCB = QtWidgets.QCheckBox(self.Spectrum)
        self.SEMUCB.setGeometry(QtCore.QRect(330, 400, 131, 21))
        self.SEMUCB.setChecked(True)
        self.SEMUCB.setObjectName("SEMUCB")
        self.S362ANI = QtWidgets.QCheckBox(self.Spectrum)
        self.S362ANI.setGeometry(QtCore.QRect(330, 430, 131, 21))
        self.S362ANI.setChecked(True)
        self.S362ANI.setObjectName("S362ANI")
        self.plot_spec = QtWidgets.QPushButton(self.Spectrum)
        self.plot_spec.setGeometry(QtCore.QRect(930, 90, 110, 32))
        self.plot_spec.setObjectName("plot_spec")
        self.savefig_spec = QtWidgets.QPushButton(self.Spectrum)
        self.savefig_spec.setGeometry(QtCore.QRect(920, 130, 131, 32))
        self.savefig_spec.setObjectName("savefig_spec")
        self.label_25 = QtWidgets.QLabel(self.Spectrum)
        self.label_25.setGeometry(QtCore.QRect(580, 570, 191, 20))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.HSdeg_spec = QtWidgets.QDoubleSpinBox(self.Spectrum)
        self.HSdeg_spec.setGeometry(QtCore.QRect(630, 590, 91, 24))
        self.HSdeg_spec.setAlignment(QtCore.Qt.AlignCenter)
        self.HSdeg_spec.setDecimals(0)
        self.HSdeg_spec.setMinimum(1.0)
        self.HSdeg_spec.setMaximum(60.0)
        self.HSdeg_spec.setSingleStep(1.0)
        self.HSdeg_spec.setProperty("value", 40.0)
        self.HSdeg_spec.setObjectName("HSdeg_spec")
        self.saveoutput_spec = QtWidgets.QPushButton(self.Spectrum)
        self.saveoutput_spec.setGeometry(QtCore.QRect(920, 170, 131, 32))
        self.saveoutput_spec.setObjectName("saveoutput_spec")
        self.label_30 = QtWidgets.QLabel(self.Spectrum)
        self.label_30.setGeometry(QtCore.QRect(630, 370, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.loadfile_spec = QtWidgets.QPushButton(self.Spectrum)
        self.loadfile_spec.setGeometry(QtCore.QRect(640, 400, 110, 32))
        self.loadfile_spec.setObjectName("loadfile_spec")
        self.label_31 = QtWidgets.QLabel(self.Spectrum)
        self.label_31.setGeometry(QtCore.QRect(520, 430, 351, 16))
        self.label_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_31.setText("")
        self.label_31.setObjectName("label_31")
        self.line_7 = QtWidgets.QFrame(self.Spectrum)
        self.line_7.setGeometry(QtCore.QRect(200, 350, 681, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.Spectrum)
        self.line_8.setGeometry(QtCore.QRect(200, 620, 681, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.Spectrum)
        self.line_9.setGeometry(QtCore.QRect(190, 360, 20, 271))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.Spectrum)
        self.line_10.setGeometry(QtCore.QRect(870, 360, 20, 271))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.SEISGLOB1 = QtWidgets.QCheckBox(self.Spectrum)
        self.SEISGLOB1.setGeometry(QtCore.QRect(210, 460, 101, 20))
        self.SEISGLOB1.setChecked(True)
        self.SEISGLOB1.setObjectName("SEISGLOB1")
        self.SP12RTS = QtWidgets.QCheckBox(self.Spectrum)
        self.SP12RTS.setGeometry(QtCore.QRect(330, 460, 101, 20))
        self.SP12RTS.setChecked(True)
        self.SP12RTS.setObjectName("SP12RTS")
        self.norm = QtWidgets.QCheckBox(self.Spectrum)
        self.norm.setGeometry(QtCore.QRect(600, 490, 151, 20))
        self.norm.setChecked(False)
        self.norm.setObjectName("norm")
        self.SGLOBE = QtWidgets.QCheckBox(self.Spectrum)
        self.SGLOBE.setGeometry(QtCore.QRect(210, 490, 101, 20))
        self.SGLOBE.setChecked(True)
        self.SGLOBE.setObjectName("SGLOBE")
        self.YOURMODEL = QtWidgets.QCheckBox(self.Spectrum)
        self.YOURMODEL.setEnabled(True)
        self.YOURMODEL.setGeometry(QtCore.QRect(210, 530, 121, 20))
        self.YOURMODEL.setChecked(False)
        self.YOURMODEL.setObjectName("YOURMODEL")
        self.D2016 = QtWidgets.QCheckBox(self.Spectrum)
        self.D2016.setGeometry(QtCore.QRect(330, 490, 101, 20))
        self.D2016.setChecked(True)
        self.D2016.setObjectName("D2016")
        self.tabWidget.addTab(self.Spectrum, "")
        self.Correlation = QtWidgets.QWidget()
        self.Correlation.setObjectName("Correlation")
        self.mapfig_corr = Qt5MplCanvas(self.Correlation)
        self.mapfig_corr.setEnabled(True)
        self.mapfig_corr.setGeometry(QtCore.QRect(160, 0, 751, 351))
        self.mapfig_corr.setMinimumSize(QtCore.QSize(150, 100))
        self.mapfig_corr.setMaximumSize(QtCore.QSize(800, 700))
        self.mapfig_corr.setObjectName("mapfig_corr")
        self.label_26 = QtWidgets.QLabel(self.Correlation)
        self.label_26.setGeometry(QtCore.QRect(440, 370, 191, 20))
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.Correlation)
        self.label_27.setGeometry(QtCore.QRect(350, 500, 131, 20))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.depth1_corr = QtWidgets.QDoubleSpinBox(self.Correlation)
        self.depth1_corr.setGeometry(QtCore.QRect(240, 520, 91, 24))
        self.depth1_corr.setAlignment(QtCore.Qt.AlignCenter)
        self.depth1_corr.setDecimals(0)
        self.depth1_corr.setMinimum(0.0)
        self.depth1_corr.setMaximum(2890.0)
        self.depth1_corr.setSingleStep(1.0)
        self.depth1_corr.setProperty("value", 2890.0)
        self.depth1_corr.setObjectName("depth1_corr")
        self.plot_corr = QtWidgets.QPushButton(self.Correlation)
        self.plot_corr.setGeometry(QtCore.QRect(940, 90, 110, 32))
        self.plot_corr.setObjectName("plot_corr")
        self.savefig_corr = QtWidgets.QPushButton(self.Correlation)
        self.savefig_corr.setGeometry(QtCore.QRect(930, 130, 131, 32))
        self.savefig_corr.setObjectName("savefig_corr")
        self.HSdeg_corr = QtWidgets.QDoubleSpinBox(self.Correlation)
        self.HSdeg_corr.setGeometry(QtCore.QRect(500, 390, 91, 24))
        self.HSdeg_corr.setAlignment(QtCore.Qt.AlignCenter)
        self.HSdeg_corr.setDecimals(0)
        self.HSdeg_corr.setMinimum(1.0)
        self.HSdeg_corr.setMaximum(60.0)
        self.HSdeg_corr.setSingleStep(1.0)
        self.HSdeg_corr.setProperty("value", 40.0)
        self.HSdeg_corr.setObjectName("HSdeg_corr")
        self.parameter1_corr = QtWidgets.QComboBox(self.Correlation)
        self.parameter1_corr.setGeometry(QtCore.QRect(370, 520, 91, 26))
        self.parameter1_corr.setEditable(False)
        self.parameter1_corr.setMaxVisibleItems(3)
        self.parameter1_corr.setDuplicatesEnabled(True)
        self.parameter1_corr.setObjectName("parameter1_corr")
        self.parameter1_corr.addItem("")
        self.parameter1_corr.addItem("")
        self.parameter1_corr.addItem("")
        self.label_29 = QtWidgets.QLabel(self.Correlation)
        self.label_29.setGeometry(QtCore.QRect(240, 500, 71, 16))
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_32 = QtWidgets.QLabel(self.Correlation)
        self.label_32.setGeometry(QtCore.QRect(280, 560, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.loadfile1_corr = QtWidgets.QPushButton(self.Correlation)
        self.loadfile1_corr.setGeometry(QtCore.QRect(290, 580, 110, 32))
        self.loadfile1_corr.setObjectName("loadfile1_corr")
        self.label_28 = QtWidgets.QLabel(self.Correlation)
        self.label_28.setGeometry(QtCore.QRect(250, 430, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_33 = QtWidgets.QLabel(self.Correlation)
        self.label_33.setGeometry(QtCore.QRect(170, 610, 351, 16))
        self.label_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_33.setText("")
        self.label_33.setObjectName("label_33")
        self.line_11 = QtWidgets.QFrame(self.Correlation)
        self.line_11.setGeometry(QtCore.QRect(159, 410, 751, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.Correlation)
        self.line_12.setGeometry(QtCore.QRect(150, 420, 20, 211))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(self.Correlation)
        self.line_13.setGeometry(QtCore.QRect(160, 620, 746, 20))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(self.Correlation)
        self.line_14.setGeometry(QtCore.QRect(530, 419, 20, 211))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.model1_corr = QtWidgets.QComboBox(self.Correlation)
        self.model1_corr.setGeometry(QtCore.QRect(280, 460, 131, 26))
        self.model1_corr.setEditable(False)
        self.model1_corr.setMaxVisibleItems(4)
        self.model1_corr.setDuplicatesEnabled(True)
        self.model1_corr.setObjectName("model1_corr")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.model1_corr.addItem("")
        self.label_35 = QtWidgets.QLabel(self.Correlation)
        self.label_35.setGeometry(QtCore.QRect(620, 430, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.model2_corr = QtWidgets.QComboBox(self.Correlation)
        self.model2_corr.setGeometry(QtCore.QRect(650, 460, 131, 26))
        self.model2_corr.setEditable(False)
        self.model2_corr.setMaxVisibleItems(4)
        self.model2_corr.setDuplicatesEnabled(True)
        self.model2_corr.setObjectName("model2_corr")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.model2_corr.addItem("")
        self.line_15 = QtWidgets.QFrame(self.Correlation)
        self.line_15.setGeometry(QtCore.QRect(900, 420, 20, 211))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.loadfile2_corr = QtWidgets.QPushButton(self.Correlation)
        self.loadfile2_corr.setGeometry(QtCore.QRect(670, 580, 110, 32))
        self.loadfile2_corr.setObjectName("loadfile2_corr")
        self.label_34 = QtWidgets.QLabel(self.Correlation)
        self.label_34.setGeometry(QtCore.QRect(660, 560, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_36 = QtWidgets.QLabel(self.Correlation)
        self.label_36.setGeometry(QtCore.QRect(620, 500, 71, 16))
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.parameter2_corr = QtWidgets.QComboBox(self.Correlation)
        self.parameter2_corr.setGeometry(QtCore.QRect(750, 520, 91, 26))
        self.parameter2_corr.setEditable(False)
        self.parameter2_corr.setMaxVisibleItems(3)
        self.parameter2_corr.setDuplicatesEnabled(True)
        self.parameter2_corr.setObjectName("parameter2_corr")
        self.parameter2_corr.addItem("")
        self.parameter2_corr.addItem("")
        self.parameter2_corr.addItem("")
        self.label_37 = QtWidgets.QLabel(self.Correlation)
        self.label_37.setGeometry(QtCore.QRect(550, 610, 351, 16))
        self.label_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.Correlation)
        self.label_38.setGeometry(QtCore.QRect(730, 500, 131, 20))
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.depth2_corr = QtWidgets.QDoubleSpinBox(self.Correlation)
        self.depth2_corr.setGeometry(QtCore.QRect(620, 520, 91, 24))
        self.depth2_corr.setAlignment(QtCore.Qt.AlignCenter)
        self.depth2_corr.setDecimals(0)
        self.depth2_corr.setMinimum(0.0)
        self.depth2_corr.setMaximum(2890.0)
        self.depth2_corr.setSingleStep(1.0)
        self.depth2_corr.setProperty("value", 2890.0)
        self.depth2_corr.setObjectName("depth2_corr")
        self.saveoutput_corr = QtWidgets.QPushButton(self.Correlation)
        self.saveoutput_corr.setGeometry(QtCore.QRect(930, 170, 131, 32))
        self.saveoutput_corr.setObjectName("saveoutput_corr")
        self.tabWidget.addTab(self.Correlation, "")
        self.Path = QtWidgets.QWidget()
        self.Path.setObjectName("Path")
        self.mapfig_path = Qt5MplCanvas(self.Path)
        self.mapfig_path.setEnabled(True)
        self.mapfig_path.setGeometry(QtCore.QRect(300, 0, 470, 351))
        self.mapfig_path.setMinimumSize(QtCore.QSize(150, 100))
        self.mapfig_path.setMaximumSize(QtCore.QSize(470, 400))
        self.mapfig_path.setObjectName("mapfig_path")
        self.loadfile_path = QtWidgets.QPushButton(self.Path)
        self.loadfile_path.setGeometry(QtCore.QRect(280, 370, 161, 32))
        self.loadfile_path.setObjectName("loadfile_path")
        self.label_45 = QtWidgets.QLabel(self.Path)
        self.label_45.setGeometry(QtCore.QRect(180, 400, 351, 16))
        self.label_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_45.setText("")
        self.label_45.setObjectName("label_45")
        self.depthmin_path = QtWidgets.QDoubleSpinBox(self.Path)
        self.depthmin_path.setGeometry(QtCore.QRect(580, 400, 91, 24))
        self.depthmin_path.setAlignment(QtCore.Qt.AlignCenter)
        self.depthmin_path.setDecimals(0)
        self.depthmin_path.setMinimum(0.0)
        self.depthmin_path.setMaximum(2890.0)
        self.depthmin_path.setSingleStep(1.0)
        self.depthmin_path.setProperty("value", 0.0)
        self.depthmin_path.setObjectName("depthmin_path")
        self.width_path = QtWidgets.QDoubleSpinBox(self.Path)
        self.width_path.setGeometry(QtCore.QRect(720, 440, 91, 24))
        self.width_path.setAlignment(QtCore.Qt.AlignCenter)
        self.width_path.setDecimals(0)
        self.width_path.setMinimum(10.0)
        self.width_path.setMaximum(360.0)
        self.width_path.setSingleStep(1.0)
        self.width_path.setProperty("value", 180.0)
        self.width_path.setObjectName("width_path")
        self.label_46 = QtWidgets.QLabel(self.Path)
        self.label_46.setGeometry(QtCore.QRect(730, 420, 71, 16))
        self.label_46.setAlignment(QtCore.Qt.AlignCenter)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.Path)
        self.label_47.setGeometry(QtCore.QRect(580, 380, 91, 20))
        self.label_47.setAlignment(QtCore.Qt.AlignCenter)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.Path)
        self.label_48.setGeometry(QtCore.QRect(180, 450, 351, 16))
        self.label_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_48.setText("")
        self.label_48.setObjectName("label_48")
        self.loadfile_eq = QtWidgets.QPushButton(self.Path)
        self.loadfile_eq.setGeometry(QtCore.QRect(280, 420, 161, 32))
        self.loadfile_eq.setObjectName("loadfile_eq")
        self.loadfile_st = QtWidgets.QPushButton(self.Path)
        self.loadfile_st.setGeometry(QtCore.QRect(280, 470, 161, 32))
        self.loadfile_st.setObjectName("loadfile_st")
        self.label_49 = QtWidgets.QLabel(self.Path)
        self.label_49.setGeometry(QtCore.QRect(180, 500, 351, 16))
        self.label_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.label_51 = QtWidgets.QLabel(self.Path)
        self.label_51.setGeometry(QtCore.QRect(270, 530, 181, 16))
        self.label_51.setAlignment(QtCore.Qt.AlignCenter)
        self.label_51.setObjectName("label_51")
        self.path_plot = QtWidgets.QPushButton(self.Path)
        self.path_plot.setGeometry(QtCore.QRect(800, 120, 110, 32))
        self.path_plot.setObjectName("path_plot")
        self.savefig_path = QtWidgets.QPushButton(self.Path)
        self.savefig_path.setGeometry(QtCore.QRect(790, 160, 131, 32))
        self.savefig_path.setObjectName("savefig_path")
        self.label_52 = QtWidgets.QLabel(self.Path)
        self.label_52.setGeometry(QtCore.QRect(110, 20, 181, 20))
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.Vmax_3 = QtWidgets.QDoubleSpinBox(self.Path)
        self.Vmax_3.setGeometry(QtCore.QRect(150, 40, 91, 24))
        self.Vmax_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Vmax_3.setDecimals(1)
        self.Vmax_3.setMaximum(20.0)
        self.Vmax_3.setSingleStep(0.5)
        self.Vmax_3.setProperty("value", 2.0)
        self.Vmax_3.setObjectName("Vmax_3")
        self.depthmax_path = QtWidgets.QDoubleSpinBox(self.Path)
        self.depthmax_path.setGeometry(QtCore.QRect(580, 460, 91, 24))
        self.depthmax_path.setAlignment(QtCore.Qt.AlignCenter)
        self.depthmax_path.setDecimals(0)
        self.depthmax_path.setMinimum(0.0)
        self.depthmax_path.setMaximum(2900.0)
        self.depthmax_path.setSingleStep(0.0)
        self.depthmax_path.setProperty("value", 2890.0)
        self.depthmax_path.setObjectName("depthmax_path")
        self.label_53 = QtWidgets.QLabel(self.Path)
        self.label_53.setGeometry(QtCore.QRect(580, 440, 101, 20))
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.depthstep_path = QtWidgets.QDoubleSpinBox(self.Path)
        self.depthstep_path.setGeometry(QtCore.QRect(580, 520, 91, 24))
        self.depthstep_path.setAlignment(QtCore.Qt.AlignCenter)
        self.depthstep_path.setDecimals(0)
        self.depthstep_path.setMinimum(0.0)
        self.depthstep_path.setMaximum(1000.0)
        self.depthstep_path.setSingleStep(1.0)
        self.depthstep_path.setProperty("value", 5.0)
        self.depthstep_path.setObjectName("depthstep_path")
        self.label_54 = QtWidgets.QLabel(self.Path)
        self.label_54.setGeometry(QtCore.QRect(580, 500, 101, 20))
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.widthstep_path = QtWidgets.QDoubleSpinBox(self.Path)
        self.widthstep_path.setGeometry(QtCore.QRect(720, 490, 91, 24))
        self.widthstep_path.setAlignment(QtCore.Qt.AlignCenter)
        self.widthstep_path.setDecimals(0)
        self.widthstep_path.setMinimum(1.0)
        self.widthstep_path.setMaximum(20.0)
        self.widthstep_path.setSingleStep(1.0)
        self.widthstep_path.setProperty("value", 1.0)
        self.widthstep_path.setObjectName("widthstep_path")
        self.label_55 = QtWidgets.QLabel(self.Path)
        self.label_55.setGeometry(QtCore.QRect(710, 470, 111, 20))
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.parameter_6 = QtWidgets.QComboBox(self.Path)
        self.parameter_6.setGeometry(QtCore.QRect(150, 100, 91, 26))
        self.parameter_6.setEditable(False)
        self.parameter_6.setMaxVisibleItems(3)
        self.parameter_6.setDuplicatesEnabled(True)
        self.parameter_6.setObjectName("parameter_6")
        self.parameter_6.addItem("")
        self.parameter_6.addItem("")
        self.parameter_6.addItem("")
        self.label_56 = QtWidgets.QLabel(self.Path)
        self.label_56.setGeometry(QtCore.QRect(130, 80, 131, 20))
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.lineEdit = QtWidgets.QLineEdit(self.Path)
        self.lineEdit.setGeometry(QtCore.QRect(180, 550, 351, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_57 = QtWidgets.QLabel(self.Path)
        self.label_57.setGeometry(QtCore.QRect(80, 140, 221, 20))
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.parameter_7 = QtWidgets.QComboBox(self.Path)
        self.parameter_7.setGeometry(QtCore.QRect(150, 160, 91, 26))
        self.parameter_7.setEditable(False)
        self.parameter_7.setMaxVisibleItems(3)
        self.parameter_7.setDuplicatesEnabled(True)
        self.parameter_7.setObjectName("parameter_7")
        self.parameter_7.addItem("")
        self.parameter_7.addItem("")
        self.parameter_7.addItem("")
        self.parameter_7.addItem("")
        self.parameter_7.addItem("")
        self.label_58 = QtWidgets.QLabel(self.Path)
        self.label_58.setGeometry(QtCore.QRect(60, 240, 231, 16))
        self.label_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_58.setText("")
        self.label_58.setObjectName("label_58")
        self.loadfile_model = QtWidgets.QPushButton(self.Path)
        self.loadfile_model.setGeometry(QtCore.QRect(50, 210, 251, 32))
        self.loadfile_model.setObjectName("loadfile_model")
        self.tabWidget.addTab(self.Path, "")
        self.Travel_time = QtWidgets.QWidget()
        self.Travel_time.setObjectName("Travel_time")
        self.loadfile_time = QtWidgets.QPushButton(self.Travel_time)
        self.loadfile_time.setGeometry(QtCore.QRect(80, 220, 311, 32))
        self.loadfile_time.setObjectName("loadfile_time")
        self.saveoutput_time = QtWidgets.QPushButton(self.Travel_time)
        self.saveoutput_time.setGeometry(QtCore.QRect(170, 480, 131, 32))
        self.saveoutput_time.setObjectName("saveoutput_time")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Travel_time)
        self.lineEdit_4.setGeometry(QtCore.QRect(60, 300, 351, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_115 = QtWidgets.QLabel(self.Travel_time)
        self.label_115.setGeometry(QtCore.QRect(60, 250, 351, 16))
        self.label_115.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_115.setText("")
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(self.Travel_time)
        self.label_116.setGeometry(QtCore.QRect(150, 280, 181, 16))
        self.label_116.setAlignment(QtCore.Qt.AlignCenter)
        self.label_116.setObjectName("label_116")
        self.model_time = QtWidgets.QComboBox(self.Travel_time)
        self.model_time.setGeometry(QtCore.QRect(170, 180, 131, 26))
        self.model_time.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.model_time.setEditable(False)
        self.model_time.setMaxVisibleItems(4)
        self.model_time.setDuplicatesEnabled(True)
        self.model_time.setObjectName("model_time")
        self.model_time.addItem("")
        self.model_time.addItem("")
        self.model_time.addItem("")
        self.model_time.addItem("")
        self.model_time.addItem("")
        self.model_time.addItem("")
        self.model_time.addItem("")
        self.model_time.addItem("")
        self.label_111 = QtWidgets.QLabel(self.Travel_time)
        self.label_111.setGeometry(QtCore.QRect(170, 160, 131, 20))
        self.label_111.setAlignment(QtCore.Qt.AlignCenter)
        self.label_111.setObjectName("label_111")
        self.calculate_time = QtWidgets.QPushButton(self.Travel_time)
        self.calculate_time.setGeometry(QtCore.QRect(170, 440, 131, 32))
        self.calculate_time.setObjectName("calculate_time")
        self.textEdit_time = QtWidgets.QTextEdit(self.Travel_time)
        self.textEdit_time.setGeometry(QtCore.QRect(470, 40, 541, 591))
        self.textEdit_time.setObjectName("textEdit_time")
        self.tabWidget.addTab(self.Travel_time, "")
        SeisTomoPy.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(SeisTomoPy)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1136, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuMENU = QtWidgets.QMenu(self.menuBar)
        self.menuMENU.setObjectName("menuMENU")
        SeisTomoPy.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(SeisTomoPy)
        self.statusBar.setObjectName("statusBar")
        SeisTomoPy.setStatusBar(self.statusBar)
        self.actionDocumentation = QtWidgets.QAction(SeisTomoPy)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionGood_Bye = QtWidgets.QAction(SeisTomoPy)
        self.actionGood_Bye.setObjectName("actionGood_Bye")
        self.menuMENU.addAction(self.actionDocumentation)
        self.menuMENU.addAction(self.actionGood_Bye)
        self.menuBar.addAction(self.menuMENU.menuAction())

        self.retranslateUi(SeisTomoPy)
        self.tabWidget.setCurrentIndex(0)
        self.parameter_cross.setCurrentIndex(0)
        self.model_cross.setCurrentIndex(0)
        self.model_map.setCurrentIndex(0)
        self.parameter_map.setCurrentIndex(0)
        self.parameter_spec.setCurrentIndex(0)
        self.parameter1_corr.setCurrentIndex(0)
        self.model1_corr.setCurrentIndex(0)
        self.model2_corr.setCurrentIndex(0)
        self.parameter2_corr.setCurrentIndex(0)
        self.parameter_6.setCurrentIndex(0)
        self.parameter_7.setCurrentIndex(0)
        self.model_time.setCurrentIndex(0)
        self.actionGood_Bye.triggered.connect(SeisTomoPy.close)
        QtCore.QMetaObject.connectSlotsByName(SeisTomoPy)

    def retranslateUi(self, SeisTomoPy):
        _translate = QtCore.QCoreApplication.translate
        SeisTomoPy.setWindowTitle(_translate("SeisTomoPy", "SeisTomoPy"))
        self.label_42.setText(_translate("SeisTomoPy", "Tools for exploiting tomographic models... AND DO MORE ! "))
        self.label_43.setText(_translate("SeisTomoPy", "Copyright, S. Durand et al. (2018)"))
        self.label_44.setText(_translate("SeisTomoPy", "SeisTomoPy: Fast visualization, comparison and calculations in spherical tomographic models"))
        self.label_50.setText(_translate("SeisTomoPy", "Seis. Res. Lett., 89(2A), 658-667"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Welcome), _translate("SeisTomoPy", "Welcome"))
        self.label_7.setText(_translate("SeisTomoPy", "Latitude"))
        self.label_5.setText(_translate("SeisTomoPy", "Mid point"))
        self.label_8.setText(_translate("SeisTomoPy", "Longitude"))
        self.label_14.setText(_translate("SeisTomoPy", "Parameter"))
        self.label_3.setText(_translate("SeisTomoPy", "Azimuth"))
        self.label_2.setText(_translate("SeisTomoPy", "Longitude"))
        self.label.setText(_translate("SeisTomoPy", "Latitude"))
        self.label_10.setText(_translate("SeisTomoPy", "Maximum perturbation (%)"))
        self.label_4.setText(_translate("SeisTomoPy", "TextLabel"))
        self.earthquake.setText(_translate("SeisTomoPy", "earthquakes"))
        self.label_6.setText(_translate("SeisTomoPy", "Starting point"))
        self.label_9.setText(_translate("SeisTomoPy", "TextLabel"))
        self.parameter_cross.setItemText(0, _translate("SeisTomoPy", "Vs"))
        self.parameter_cross.setItemText(1, _translate("SeisTomoPy", "Vp"))
        self.parameter_cross.setItemText(2, _translate("SeisTomoPy", "density"))
        self.label_15.setText(_translate("SeisTomoPy", "Click on the map to set a profile"))
        self.savefig_cross.setText(_translate("SeisTomoPy", "SAVE FIGURE"))
        self.plot_cross.setText(_translate("SeisTomoPy", "PLOTTING"))
        self.model_cross.setItemText(0, _translate("SeisTomoPy", "SEISGLOB2"))
        self.model_cross.setItemText(1, _translate("SeisTomoPy", "S40RTS"))
        self.model_cross.setItemText(2, _translate("SeisTomoPy", "SEMUCB-WM1"))
        self.model_cross.setItemText(3, _translate("SeisTomoPy", "S362WMANI+M"))
        self.model_cross.setItemText(4, _translate("SeisTomoPy", "SEISGLOB1"))
        self.model_cross.setItemText(5, _translate("SeisTomoPy", "SP12RTS"))
        self.model_cross.setItemText(6, _translate("SeisTomoPy", "SGLOBE-rani"))
        self.model_cross.setItemText(7, _translate("SeisTomoPy", "3D2016-09S"))
        self.model_cross.setItemText(8, _translate("SeisTomoPy", "YOUR MODEL"))
        self.saveoutput_cross.setText(_translate("SeisTomoPy", "SAVE OUTPUT"))
        self.hotspots.setText(_translate("SeisTomoPy", "hotspots"))
        self.label_12.setText(_translate("SeisTomoPy", "Width (deg)"))
        self.label_11.setText(_translate("SeisTomoPy", "Depth (km)"))
        self.label_13.setText(_translate("SeisTomoPy", "Tomographic model"))
        self.label_40.setText(_translate("SeisTomoPy", "Spherical harmonic degree max"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Cross_section), _translate("SeisTomoPy", "Cross section"))
        self.label_17.setText(_translate("SeisTomoPy", "Maximum perturbation (%)"))
        self.label_18.setText(_translate("SeisTomoPy", "Tomographic model"))
        self.model_map.setItemText(0, _translate("SeisTomoPy", "SEISGLOB2"))
        self.model_map.setItemText(1, _translate("SeisTomoPy", "S40RTS"))
        self.model_map.setItemText(2, _translate("SeisTomoPy", "SEMUCB-WM1"))
        self.model_map.setItemText(3, _translate("SeisTomoPy", "S362WMANI+M"))
        self.model_map.setItemText(4, _translate("SeisTomoPy", "SEISGLOB1"))
        self.model_map.setItemText(5, _translate("SeisTomoPy", "SP12RTS"))
        self.model_map.setItemText(6, _translate("SeisTomoPy", "SGLOBE-rani"))
        self.model_map.setItemText(7, _translate("SeisTomoPy", "3D2016-09S"))
        self.model_map.setItemText(8, _translate("SeisTomoPy", "YOUR MODEL"))
        self.label_19.setText(_translate("SeisTomoPy", "Parameter"))
        self.parameter_map.setItemText(0, _translate("SeisTomoPy", "Vs"))
        self.parameter_map.setItemText(1, _translate("SeisTomoPy", "Vp"))
        self.parameter_map.setItemText(2, _translate("SeisTomoPy", "density"))
        self.parameter_map.setItemText(3, _translate("SeisTomoPy", "Temperature"))
        self.savefig_map.setText(_translate("SeisTomoPy", "SAVE FIGURE"))
        self.plot_map.setText(_translate("SeisTomoPy", "PLOTTING"))
        self.hotspots_map.setText(_translate("SeisTomoPy", "hotspots"))
        self.plateboundaries.setText(_translate("SeisTomoPy", "plate boundaries"))
        self.label_21.setText(_translate("SeisTomoPy", "Depth (km)"))
        self.saveoutput_map.setText(_translate("SeisTomoPy", "SAVE OUTPUT"))
        self.label_39.setText(_translate("SeisTomoPy", "Spherical harmonic degree max"))
        self.label_41.setText(_translate("SeisTomoPy", "Central longitude"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Map), _translate("SeisTomoPy", "Map"))
        self.label_22.setText(_translate("SeisTomoPy", "Depth (km)"))
        self.label_23.setText(_translate("SeisTomoPy", "Tomographic models"))
        self.label_24.setText(_translate("SeisTomoPy", "Parameter"))
        self.parameter_spec.setItemText(0, _translate("SeisTomoPy", "Vs"))
        self.parameter_spec.setItemText(1, _translate("SeisTomoPy", "Vp"))
        self.parameter_spec.setItemText(2, _translate("SeisTomoPy", "Density"))
        self.SEISGLOB2.setText(_translate("SeisTomoPy", "SEISGLOB2"))
        self.S40RTS.setText(_translate("SeisTomoPy", "S40RTS"))
        self.SEMUCB.setText(_translate("SeisTomoPy", "SEMUCB-WM1"))
        self.S362ANI.setText(_translate("SeisTomoPy", "S362WMANI+M"))
        self.plot_spec.setText(_translate("SeisTomoPy", "PLOTTING"))
        self.savefig_spec.setText(_translate("SeisTomoPy", "SAVE FIGURE"))
        self.label_25.setText(_translate("SeisTomoPy", "Spherical harmonic degree max"))
        self.saveoutput_spec.setText(_translate("SeisTomoPy", "SAVE OUTPUT"))
        self.label_30.setText(_translate("SeisTomoPy", "Select a file"))
        self.loadfile_spec.setText(_translate("SeisTomoPy", "load"))
        self.SEISGLOB1.setText(_translate("SeisTomoPy", "SEISGLOB1"))
        self.SP12RTS.setText(_translate("SeisTomoPy", "SP12RTS"))
        self.norm.setText(_translate("SeisTomoPy", "normalize spectrum"))
        self.SGLOBE.setText(_translate("SeisTomoPy", "SGLOBE-rani"))
        self.YOURMODEL.setText(_translate("SeisTomoPy", "MY MODEL"))
        self.D2016.setText(_translate("SeisTomoPy", "3D2016-09S"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Spectrum), _translate("SeisTomoPy", "Spectrum"))
        self.label_26.setText(_translate("SeisTomoPy", "Spherical harmonic degree max"))
        self.label_27.setText(_translate("SeisTomoPy", "Parameter"))
        self.plot_corr.setText(_translate("SeisTomoPy", "PLOTTING"))
        self.savefig_corr.setText(_translate("SeisTomoPy", "SAVE FIGURE"))
        self.parameter1_corr.setItemText(0, _translate("SeisTomoPy", "Vs"))
        self.parameter1_corr.setItemText(1, _translate("SeisTomoPy", "Vp"))
        self.parameter1_corr.setItemText(2, _translate("SeisTomoPy", "Density"))
        self.label_29.setText(_translate("SeisTomoPy", "Depth (km)"))
        self.label_32.setText(_translate("SeisTomoPy", "Select a file"))
        self.loadfile1_corr.setText(_translate("SeisTomoPy", "load"))
        self.label_28.setText(_translate("SeisTomoPy", "Tomographic models"))
        self.model1_corr.setItemText(0, _translate("SeisTomoPy", "SEISGLOB2"))
        self.model1_corr.setItemText(1, _translate("SeisTomoPy", "S40RTS"))
        self.model1_corr.setItemText(2, _translate("SeisTomoPy", "SEMUCB-WM1"))
        self.model1_corr.setItemText(3, _translate("SeisTomoPy", "S362WMANI+M"))
        self.model1_corr.setItemText(4, _translate("SeisTomoPy", "SEISGLOB1"))
        self.model1_corr.setItemText(5, _translate("SeisTomoPy", "SP12RTS"))
        self.model1_corr.setItemText(6, _translate("SeisTomoPy", "SGLOBE-rani"))
        self.model1_corr.setItemText(7, _translate("SeisTomoPy", "3D2016-09S"))
        self.model1_corr.setItemText(8, _translate("SeisTomoPy", "YOUR MODEL"))
        self.model1_corr.setItemText(9, _translate("SeisTomoPy", "None"))
        self.label_35.setText(_translate("SeisTomoPy", "Tomographic models"))
        self.model2_corr.setItemText(0, _translate("SeisTomoPy", "SEISGLOB2"))
        self.model2_corr.setItemText(1, _translate("SeisTomoPy", "S40RTS"))
        self.model2_corr.setItemText(2, _translate("SeisTomoPy", "SEMUCB-WM1"))
        self.model2_corr.setItemText(3, _translate("SeisTomoPy", "S362WMANI+M"))
        self.model2_corr.setItemText(4, _translate("SeisTomoPy", "SEISGLOB1"))
        self.model2_corr.setItemText(5, _translate("SeisTomoPy", "SP12RTS"))
        self.model2_corr.setItemText(6, _translate("SeisTomoPy", "SGLOBE-rani"))
        self.model2_corr.setItemText(7, _translate("SeisTomoPy", "3D2016-09S"))
        self.model2_corr.setItemText(8, _translate("SeisTomoPy", "YOUR MODEL"))
        self.model2_corr.setItemText(9, _translate("SeisTomoPy", "None"))
        self.loadfile2_corr.setText(_translate("SeisTomoPy", "load"))
        self.label_34.setText(_translate("SeisTomoPy", "Select a file"))
        self.label_36.setText(_translate("SeisTomoPy", "Depth (km)"))
        self.parameter2_corr.setItemText(0, _translate("SeisTomoPy", "Vs"))
        self.parameter2_corr.setItemText(1, _translate("SeisTomoPy", "Vp"))
        self.parameter2_corr.setItemText(2, _translate("SeisTomoPy", "Density"))
        self.label_38.setText(_translate("SeisTomoPy", "Parameter"))
        self.saveoutput_corr.setText(_translate("SeisTomoPy", "SAVE OUTPUT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Correlation), _translate("SeisTomoPy", "Correlation"))
        self.loadfile_path.setText(_translate("SeisTomoPy", "load cross-section"))
        self.label_46.setText(_translate("SeisTomoPy", "Width (deg)"))
        self.label_47.setText(_translate("SeisTomoPy", "Depth min (km)"))
        self.loadfile_eq.setText(_translate("SeisTomoPy", "load earthquake file"))
        self.loadfile_st.setText(_translate("SeisTomoPy", "load station file"))
        self.label_51.setText(_translate("SeisTomoPy", "List of seismic phases"))
        self.path_plot.setText(_translate("SeisTomoPy", "PLOTTING"))
        self.savefig_path.setText(_translate("SeisTomoPy", "SAVE FIGURE"))
        self.label_52.setText(_translate("SeisTomoPy", "Maximum perturbation (%)"))
        self.label_53.setText(_translate("SeisTomoPy", "Depth max (km)"))
        self.label_54.setText(_translate("SeisTomoPy", "Depth step (km)"))
        self.label_55.setText(_translate("SeisTomoPy", "Width step (deg)"))
        self.parameter_6.setItemText(0, _translate("SeisTomoPy", "Vs"))
        self.parameter_6.setItemText(1, _translate("SeisTomoPy", "Vp"))
        self.parameter_6.setItemText(2, _translate("SeisTomoPy", "density"))
        self.label_56.setText(_translate("SeisTomoPy", "Parameter"))
        self.label_57.setText(_translate("SeisTomoPy", "1-D model for path calculations"))
        self.parameter_7.setItemText(0, _translate("SeisTomoPy", "PREM"))
        self.parameter_7.setItemText(1, _translate("SeisTomoPy", "iasp91"))
        self.parameter_7.setItemText(2, _translate("SeisTomoPy", "ak135"))
        self.parameter_7.setItemText(3, _translate("SeisTomoPy", "pwdk"))
        self.parameter_7.setItemText(4, _translate("SeisTomoPy", "None"))
        self.loadfile_model.setText(_translate("SeisTomoPy", "load model file for path calculations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Path), _translate("SeisTomoPy", "Path"))
        self.loadfile_time.setText(_translate("SeisTomoPy", "load earthquake and station file"))
        self.saveoutput_time.setText(_translate("SeisTomoPy", "SAVE OUTPUT"))
        self.label_116.setText(_translate("SeisTomoPy", "List of seismic phases"))
        self.model_time.setItemText(0, _translate("SeisTomoPy", "SEISGLOB2"))
        self.model_time.setItemText(1, _translate("SeisTomoPy", "S40RTS"))
        self.model_time.setItemText(2, _translate("SeisTomoPy", "SEMUCB-WM1"))
        self.model_time.setItemText(3, _translate("SeisTomoPy", "S362WMANI+M"))
        self.model_time.setItemText(4, _translate("SeisTomoPy", "SEISGLOB1"))
        self.model_time.setItemText(5, _translate("SeisTomoPy", "SP12RTS"))
        self.model_time.setItemText(6, _translate("SeisTomoPy", "SGLOBE-rani"))
        self.model_time.setItemText(7, _translate("SeisTomoPy", "YOUR MODEL"))
        self.label_111.setText(_translate("SeisTomoPy", "Tomographic model"))
        self.calculate_time.setText(_translate("SeisTomoPy", "CALCULATE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Travel_time), _translate("SeisTomoPy", "Travel time"))
        self.menuMENU.setTitle(_translate("SeisTomoPy", "MENU"))
        self.actionDocumentation.setText(_translate("SeisTomoPy", "Documentation"))
        self.actionGood_Bye.setText(_translate("SeisTomoPy", "Good Bye !"))

from SeisTomoPy.gui.qt5mplcanvas import Qt5MplCanvas
